# Generated by Django 5.0.3 on 2024-03-26 15:36

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=2)),
                ('description', models.TextField()),
                ('date_range', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('price', django.contrib.postgres.fields.ranges.IntegerRangeField()),
            ],
        ),
    ]
